version: '3.7'

services:
  backend:
    image: node:16.15.0-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - database
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - my-network
    environment:
      - POSTGRES_USER=maks
      - POSTGRES_PASSWORD=maks
      - POSTGRES_DB=hospital
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgres
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data:
